/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Invitation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'createInvitation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
  'getInvitation' : IDL.Func([IDL.Text], [Invitation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Invitation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'createInvitation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
    'getInvitation' : IDL.Func([IDL.Text], [Invitation], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };